# Generated by Django 6.0.3 on 2026-03-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentic", "0001_initial"),
        ("tasks", "0002_restaurant_alter_deliverytask_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.restaurant",
            ),
        ),
    ]
